language: rust
cache: cargo
matrix:
  include:
    - rust: stable
      env: FEATURES=""
    - rust: stable
      env: FEATURES="serde-1"
script:
  - cargo test --verbose --no-default-features --features "$FEATURES"
